# Bot Information
[info]
name = "ÙƒØ§ØºÙˆÙŠØ§ Ø§Ù„Ø¨ÙˆØª"
version = "Ø§Ù„Ø¨ÙˆØª Ù‡Ùˆ Ø­Ø§Ù„ÙŠØ§ ÙÙŠ Ø£ØµØ¯Ø§Ø± : $1"
author = "Ø­Ø³ÙŠÙ† ÙŠØ¹Ù‚ÙˆØ¨ÙŠ"
title_process = "ÙƒØ§ØºÙˆÙŠØ§ Ø§Ù„Ø¨ÙˆØª - $1:$2:$3"

# Index
[index]
host = "Ø§Ù„Ø§Ø³ØªÙ…Ø§Ø¹ Ø¹Ù„Ù‰ Ø§Ù„Ù…ÙŠÙ†Ø§Ø¡ : $1"
invalid_credentials = "ÙŠØ±Ø¬Ù‰ Ø§Ù„Ø°Ù‡Ø§Ø¨ Ø¥Ù„Ù‰ setup/credentials.json Ù…Ù„Ù ÙˆØ§Ù…Ù„Ø£ fbstate!"
exists_credentials = "ØªÙ… Ø§ÙŠØ¬Ø§Ø¯ credentials.json file -> Ø¬Ø§Ø±ÙŠ Ø§Ù„Ù…Ø¶ÙŠ Ù‚Ø¯Ù…Ø§ ÙÙŠ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„!..."
login_success = "ØªÙ… Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¨Ù†Ø¬Ø§Ø­ !"
login_error = "ÙØ´Ù„ Ø§Ù„Ø¯Ø®ÙˆÙ„ !"
listen = "Ø§Ù„Ø§Ø³ØªÙ…Ø§Ø¹ Ø­Ø§Ù„ÙŠØ§ Ù„Ù„Ø£Ø­Ø¯Ø§Ø« Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø© !"
update = "Ø§Ù„Ø¨ÙˆØª Ø­Ø§Ù„ÙŠØ§ Ù„Ø¯ÙŠÙ‡ Ø¥ØµØ¯Ø§Ø± Ø¬Ø¯ÙŠØ¯ $1 -> $2! Ø§Ù„Ù…Ø±Ø¬Ùˆ ØªØ­Ø¯ÙŠØ«Ù‡ Ø¹Ù„Ù‰ Ø¢Ø®Ø± Ø¥ØµØ¯Ø§Ø± : https://github.com/ttkienn/kaguya-project"
refresh_mqtt = "Refreshing MQTT in progress!"
refresh_mqtt_success = "MQTT refresh successful!"

# Database
[database]
type = "You have chosen the database type as: $1"
connection_success = "Connected to the database successfully!"
connection_failed = "Unable to connect to the database!"
create_user = "Successfully created data for the user: $1"
create_thread = "Successfully created data for the group: $1"

# Handler
[handler]
command_load = " âœ… |ØªÙ… ØªØ­Ù…ÙŠÙ„ Ø§Ù„Ø£Ù…Ø± Ø¨Ù†Ø¬Ø§Ø­ : $1"
command_load_error = " âŒ |ØºÙŠØ± Ù‚Ø§Ø¯Ø± Ø¹Ù„Ù‰ ØªØ­Ù…ÙŠÙ„ Ø§Ù„Ø£Ù…Ø± : $1 ÙŠØªØ¹Ù„Ù‚ Ø°Ø§Ù„Ùƒ Ø¨Ø§Ù„Ø®Ø·Ø£ : $2"
event_load = " âœ… | ØªÙ… ØªØ­Ù…ÙŠÙ„ Ø¨Ù†Ø¬Ø§Ø­ : $1 Ù…Ù† Ø§Ù„Ø£ÙˆØ§Ù…Ø±"
event_load_error = " âŒ | ÙØ´Ù„ ØªØ­Ù…ÙŠÙ„ Ø§Ù„Ø¥ÙŠÙÙ†ØªØ² : $1 ÙŠØªØ¹Ù„Ù‚ Ø§Ù„Ø£Ù…Ø± Ø¨Ø§Ù„Ø®Ø·Ø£ : $2"
command_noPermission = " âš ï¸ | Ù„ÙŠØ³ Ù„Ø¯ÙŠÙƒ Ø§Ù„ØµÙ„Ø§Ø­ÙŠØ© Ù„Ø¥Ø³ØªØ®Ø¯Ø§Ù… Ù‡Ø°Ø§ Ø§Ù„Ø£Ù…Ø± â—"
command_cooldowns = " â±ï¸ | Ø£Ù†Øª ØªØ­ØªØ§Ø­ ØªÙ†ØªØ¸Ø± $1 Ø«Ø§Ù†ÙŠØ© Ù„ØªØ³ØªØ®Ø¯Ù…Ù‡ Ù…Ø¬Ø¯Ø¯Ø§ !"
command_aliases_exists = " âš ï¸ | Ù…ÙŠØ²Ø© Ø§Ù„Ø£Ù„Ù‚Ø§Ø¨ $1 Ù‡ÙŠ Ø¨Ø§Ù„ÙØ¹Ù„ Ù…Ø³ØªØ®Ø¯Ù…Ø© Ø¨Ø§Ù„Ù†Ø³Ø¨Ø© Ù„Ù„Ø£Ù…Ø± $2 ØŒ Ù„Ø°Ø§Ù„Ùƒ Ù„Ø§ ÙŠÙ…ÙƒÙ† ØªØ­Ù…ÙŠÙ„ Ø§Ù„Ø£Ù…Ø± $3!"
error = " âŒ |Ø­Ø¯Ø« Ø®Ø·Ø£ : $1"
thread_ban = " âŒ | Ù…Ø¬Ù…ÙˆØ¹ØªÙƒÙ… ØªÙ… Ø­Ø¸Ø±Ù‡Ø§ Ù…Ù† Ø¥Ø³ØªØ®Ø¯Ø§Ù… ÙƒØ§ØºÙˆÙŠØ§ Ø§Ù„Ø¨ÙˆØª ÙˆØ§Ù„Ø³Ø¨Ø¨ : $1"
user_ban = "âŒ | ØªÙ… Ø­Ø¸Ø±Ùƒ Ù…Ù† Ø¥Ø³ØªØ®Ø¯Ø§Ù… ÙƒØ§ØºÙˆÙŠØ§ Ø§Ù„Ø¨ÙˆØª Ù…Ø¹ Ø§Ù„Ø³Ø¨Ø¨ : $1"
command_not_found = "Ù‡Ø§Ø°Ø§ Ø§Ù„Ø§Ù…Ø± ØºÙŠØ± Ù…ÙˆØ¬ÙˆØ¯ ðŸ™â€â™€ï¸ 
Ø§ÙƒØªØ¨ Ø§ÙˆØ§Ù…Ø± Ù„Ø§Ø±Ø£ÙŠØ© Ø§Ù„Ø§ÙˆØ§Ù…Ø± ðŸ’â€â™€ï¸âœ“"

# plugins -> example plugins help.js
[plugins]
